application: eventdatagenerator 
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /rsc
  static_dir: rsc

- url: /.*
  script: web.app

libraries:
- name: jinja2
  version: latest